/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { randInt } from "three/src/math/MathUtils.js";

type GLTFResult = GLTF & {
  nodes: {
    Boxers: THREE.SkinnedMesh;
    CC_Base_Body_1: THREE.SkinnedMesh;
    CC_Base_Body_2: THREE.SkinnedMesh;
    CC_Base_Body_3: THREE.SkinnedMesh;
    CC_Base_Body_4: THREE.SkinnedMesh;
    CC_Base_Body_5: THREE.SkinnedMesh;
    CC_Base_Body_6: THREE.SkinnedMesh;
    CC_Base_Eye_1: THREE.SkinnedMesh;
    CC_Base_Eye_2: THREE.SkinnedMesh;
    CC_Base_Eye_3: THREE.SkinnedMesh;
    CC_Base_Eye_4: THREE.SkinnedMesh;
    CC_Base_EyeOcclusion_1: THREE.SkinnedMesh;
    CC_Base_EyeOcclusion_2: THREE.SkinnedMesh;
    CC_Base_TearLine_1: THREE.SkinnedMesh;
    CC_Base_TearLine_2: THREE.SkinnedMesh;
    CC_Base_Teeth_1: THREE.SkinnedMesh;
    CC_Base_Teeth_2: THREE.SkinnedMesh;
    CC_Base_Tongue: THREE.SkinnedMesh;
    Curly_fringe_1: THREE.SkinnedMesh;
    Curly_fringe_2: THREE.SkinnedMesh;
    Fit_shirts: THREE.SkinnedMesh;
    CC_Base_BoneRoot: THREE.Bone;
  };
  materials: {
    Boxers: THREE.MeshPhysicalMaterial;
    Std_Skin_Head: THREE.MeshPhysicalMaterial;
    Std_Skin_Body: THREE.MeshPhysicalMaterial;
    Std_Skin_Arm: THREE.MeshPhysicalMaterial;
    Std_Skin_Leg: THREE.MeshPhysicalMaterial;
    Std_Nails: THREE.MeshPhysicalMaterial;
    Std_Eyelash: THREE.MeshPhysicalMaterial;
    Std_Eye_R: THREE.MeshPhysicalMaterial;
    Std_Cornea_R: THREE.MeshPhysicalMaterial;
    Std_Eye_L: THREE.MeshPhysicalMaterial;
    Std_Cornea_L: THREE.MeshPhysicalMaterial;
    Std_Eye_Occlusion_R: THREE.MeshPhysicalMaterial;
    Std_Eye_Occlusion_L: THREE.MeshPhysicalMaterial;
    Std_Tearline_R: THREE.MeshPhysicalMaterial;
    Std_Tearline_L: THREE.MeshPhysicalMaterial;
    Std_Upper_Teeth: THREE.MeshPhysicalMaterial;
    Std_Lower_Teeth: THREE.MeshPhysicalMaterial;
    Std_Tongue: THREE.MeshPhysicalMaterial;
    Scalp_Transparency: THREE.MeshPhysicalMaterial;
    Hair_Transparency: THREE.MeshPhysicalMaterial;
    Fit_shirts: THREE.MeshPhysicalMaterial;
  };
};

type ActionName =
  | "Armature|Calibration"
  | "Key.001|Calibration"
  | "Key.004|Calibration"
  | "Key.003|Calibration"
  | "Key.002|Calibration"
  | "Key|Calibration"
  | "Key.005|Calibration";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/untitled.glb"
  ) as GLTFResult;
  // const { actions } = useAnimations<GLTFActions>(animations, group)

  const { animations: sittingIdle } = useFBX("/models/sittingIdle.fbx");
  sittingIdle[0].name = "Idle";
  const { actions } = useAnimations(sittingIdle, group);

  useEffect(() => {
    actions["Idle"]!.reset().play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null} position={[0, -1.2, 0]}>
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <skinnedMesh
            name="Boxers"
            geometry={nodes.Boxers.geometry}
            material={materials.Boxers}
            skeleton={nodes.Boxers.skeleton}
          />
          <group name="CC_Base_Body">
            <skinnedMesh
              name="CC_Base_Body_1"
              geometry={nodes.CC_Base_Body_1.geometry}
              material={materials.Std_Skin_Head}
              skeleton={nodes.CC_Base_Body_1.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_1.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Body_2"
              geometry={nodes.CC_Base_Body_2.geometry}
              material={materials.Std_Skin_Body}
              skeleton={nodes.CC_Base_Body_2.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_2.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_2.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Body_3"
              geometry={nodes.CC_Base_Body_3.geometry}
              material={materials.Std_Skin_Arm}
              skeleton={nodes.CC_Base_Body_3.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_3.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_3.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Body_4"
              geometry={nodes.CC_Base_Body_4.geometry}
              material={materials.Std_Skin_Leg}
              skeleton={nodes.CC_Base_Body_4.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_4.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_4.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Body_5"
              geometry={nodes.CC_Base_Body_5.geometry}
              material={materials.Std_Nails}
              skeleton={nodes.CC_Base_Body_5.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_5.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_5.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Body_6"
              geometry={nodes.CC_Base_Body_6.geometry}
              material={materials.Std_Eyelash}
              skeleton={nodes.CC_Base_Body_6.skeleton}
              morphTargetDictionary={nodes.CC_Base_Body_6.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Body_6.morphTargetInfluences}
            />
          </group>
          <group name="CC_Base_Eye">
            <skinnedMesh
              name="CC_Base_Eye_1"
              geometry={nodes.CC_Base_Eye_1.geometry}
              material={materials.Std_Eye_R}
              skeleton={nodes.CC_Base_Eye_1.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_1.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Eye_2"
              geometry={nodes.CC_Base_Eye_2.geometry}
              material={materials.Std_Cornea_R}
              skeleton={nodes.CC_Base_Eye_2.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_2.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_2.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Eye_3"
              geometry={nodes.CC_Base_Eye_3.geometry}
              material={materials.Std_Eye_L}
              skeleton={nodes.CC_Base_Eye_3.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_3.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_3.morphTargetInfluences}
            />
            <skinnedMesh
              name="CC_Base_Eye_4"
              geometry={nodes.CC_Base_Eye_4.geometry}
              material={materials.Std_Cornea_L}
              skeleton={nodes.CC_Base_Eye_4.skeleton}
              morphTargetDictionary={nodes.CC_Base_Eye_4.morphTargetDictionary}
              morphTargetInfluences={nodes.CC_Base_Eye_4.morphTargetInfluences}
            />
          </group>
          <group name="CC_Base_EyeOcclusion">
            <skinnedMesh
              name="CC_Base_EyeOcclusion_1"
              geometry={nodes.CC_Base_EyeOcclusion_1.geometry}
              material={materials.Std_Eye_Occlusion_R}
              skeleton={nodes.CC_Base_EyeOcclusion_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_EyeOcclusion_2"
              geometry={nodes.CC_Base_EyeOcclusion_2.geometry}
              material={materials.Std_Eye_Occlusion_L}
              skeleton={nodes.CC_Base_EyeOcclusion_2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_EyeOcclusion_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_EyeOcclusion_2.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_TearLine">
            <skinnedMesh
              name="CC_Base_TearLine_1"
              geometry={nodes.CC_Base_TearLine_1.geometry}
              material={materials.Std_Tearline_R}
              skeleton={nodes.CC_Base_TearLine_1.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="CC_Base_TearLine_2"
              geometry={nodes.CC_Base_TearLine_2.geometry}
              material={materials.Std_Tearline_L}
              skeleton={nodes.CC_Base_TearLine_2.skeleton}
              morphTargetDictionary={
                nodes.CC_Base_TearLine_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.CC_Base_TearLine_2.morphTargetInfluences
              }
            />
          </group>
          <group name="CC_Base_Teeth">
            <skinnedMesh
              name="CC_Base_Teeth_1"
              geometry={nodes.CC_Base_Teeth_1.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_1.skeleton}
            />
            <skinnedMesh
              name="CC_Base_Teeth_2"
              geometry={nodes.CC_Base_Teeth_2.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="CC_Base_Tongue"
            geometry={nodes.CC_Base_Tongue.geometry}
            material={materials.Std_Tongue}
            skeleton={nodes.CC_Base_Tongue.skeleton}
            morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
          />
          <group name="Curly_fringe">
            <skinnedMesh
              name="Curly_fringe_1"
              geometry={nodes.Curly_fringe_1.geometry}
              material={materials.Scalp_Transparency}
              skeleton={nodes.Curly_fringe_1.skeleton}
              morphTargetDictionary={nodes.Curly_fringe_1.morphTargetDictionary}
              morphTargetInfluences={nodes.Curly_fringe_1.morphTargetInfluences}
            />
            <skinnedMesh
              name="Curly_fringe_2"
              geometry={nodes.Curly_fringe_2.geometry}
              material={materials.Hair_Transparency}
              skeleton={nodes.Curly_fringe_2.skeleton}
              morphTargetDictionary={nodes.Curly_fringe_2.morphTargetDictionary}
              morphTargetInfluences={nodes.Curly_fringe_2.morphTargetInfluences}
            />
          </group>
          <skinnedMesh
            name="Fit_shirts"
            geometry={nodes.Fit_shirts.geometry}
            material={materials.Fit_shirts}
            skeleton={nodes.Fit_shirts.skeleton}
          />
          <primitive object={nodes.CC_Base_BoneRoot} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/untitled.glb");
